hard_tabs = false                # 공백을 사용할지 여부 (true면 탭 문자, false면 공백)
tab_spaces = 2
max_width = 100
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
