// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

/** Tag를 그룹화 하는 객체입니다.
    자녀요소로 Tag를 가지고 있으며.
    카테고리를 호출 시 모든 태그를 함께 호출합니다.
*/
export type Category = { id: bigint, name: string, is_default: string, tags: Array<Tag> | null, };
