// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileInfo = { id: bigint | null, name: string, path: string, is_dir: boolean, size: bigint | null, created_at: string | null, modified_at: string | null, extension: string | null, readonly: boolean, category: string | null, tags: Array<string> | null, };
