// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseStatus } from "./ResponseStatus";

export type Response<T> = { status: ResponseStatus, message: string | null, data: T | null, };
