// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/** taggingmon 에서 명명한 
   fso(file system object)라는 요소에 
   태그를 붙일 수 있습니다.

    각 fso는 태그를 갖고 있으며, 생성, 수정일자, 
    확장자를 기반으로 한 태그들은 is auto generated가 true 입니다.
*/
export type Tag = { id: bigint, category_id: bigint, name: string, is_auto_generated: string, };
